---
abstract: 'easily generate random passwords with an option to use md5_hex from Digest::MD5 on them | Pure perl solution'
author:
  - "'Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-RandomPasswordGeneratorPurePerl
provides:
  App::ZofCMS::Plugin::RandomPasswordGeneratorPurePerl:
    file: lib/App/ZofCMS/Plugin/RandomPasswordGeneratorPurePerl.pm
    version: 0.0104
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  Digest::MD5: 2.36_01
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0104
